-- Sample data inserts for Chania Skills for Africa
-- This script adds sample partners and team members to populate the database

USE chania_db;

-- Insert sample partners
INSERT INTO partners (
    name, 
    slug, 
    description, 
    logo_path, 
    website_url, 
    contact_email, 
    contact_phone, 
    contact_person, 
    partnership_type, 
    partnership_level, 
    start_date, 
    is_featured, 
    is_active, 
    display_order,
    created_by
) VALUES 
(
    'Kenya Association of Manufacturers (KAM)',
    'kenya-association-manufacturers',
    'Leading manufacturing industry association providing employment opportunities and industrial training partnerships.',
    'assets/images/partners/kam-logo.png',
    'https://kam.co.ke',
    'info@kam.co.ke',
    '+254 20 2324826',
    'Sarah Kimani',
    'employment',
    'strategic',
    '2023-01-15',
    1,
    1,
    1,
    1
),
(
    'Technical University of Kenya (TU-K)',
    'technical-university-kenya',
    'Premier technical university offering advanced training programs and certification partnerships.',
    'assets/images/partners/tuk-logo.png',
    'https://tukenya.ac.ke',
    'partnerships@tukenya.ac.ke',
    '+254 20 2219929',
    'Prof. Francis Aduol',
    'training',
    'strategic',
    '2023-03-10',
    1,
    1,
    2,
    1
),
(
    'Safaricom Foundation',
    'safaricom-foundation',
    'Supporting digital skills development and technology access for underserved communities.',
    'assets/images/partners/safaricom-logo.png',
    'https://foundation.safaricom.co.ke',
    'foundation@safaricom.co.ke',
    '+254 722 000000',
    'Peter Ndegwa',
    'funding',
    'strategic',
    '2023-02-20',
    1,
    1,
    3,
    1
),
(
    'World Bank Group',
    'world-bank-group',
    'International financial institution supporting skills development and job creation initiatives.',
    'assets/images/partners/worldbank-logo.png',
    'https://worldbank.org',
    'kenya@worldbank.org',
    '+254 20 3226300',
    'Dr. Keith Hansen',
    'funding',
    'strategic',
    '2022-11-05',
    1,
    1,
    4,
    1
),
(
    'Microsoft Kenya',
    'microsoft-kenya',
    'Technology partner providing digital literacy training and certification programs.',
    'assets/images/partners/microsoft-logo.png',
    'https://microsoft.com/kenya',
    'kenya@microsoft.com',
    '+254 20 2711077',
    'Kendi Nderitu',
    'technology',
    'standard',
    '2023-04-18',
    1,
    1,
    5,
    1
),
(
    'Equity Bank Foundation',
    'equity-bank-foundation',
    'Supporting entrepreneurship and financial literacy programs in rural communities.',
    'assets/images/partners/equity-logo.png',
    'https://equitybankfoundation.com',
    'foundation@equitybank.co.ke',
    '+254 763 026000',
    'Mary Wamae',
    'funding',
    'standard',
    '2023-06-12',
    0,
    1,
    6,
    1
);

-- Insert sample team members
INSERT INTO team_members (
    name,
    position,
    department,
    photo,
    bio,
    qualifications,
    experience_years,
    specialties,
    email,
    phone,
    linkedin,
    twitter,
    is_featured,
    is_active,
    position_order,
    hire_date,
    created_by
) VALUES 
(
    'Dr. Grace Wanjiku Maina',
    'Executive Director',
    'Leadership',
    'assets/images/team/grace-maina.jpg',
    'Dr. Grace Maina is a seasoned development practitioner with over 15 years of experience in skills development, community empowerment, and organizational leadership. She holds a PhD in Development Studies and has worked with various international organizations.',
    'PhD in Development Studies (University of Nairobi), MSc in Community Development (Kenyatta University), Certified Project Management Professional (PMP)',
    15,
    '["Leadership", "Strategic Planning", "Community Development", "Project Management"]',
    'grace.maina@skillsforafrica.org',
    '+254 722 123456',
    'https://linkedin.com/in/gracemaina',
    'https://twitter.com/gracemaina',
    1,
    1,
    1,
    '2020-01-15',
    1
),
(
    'John Kamau Njoroge',
    'Programs Manager',
    'Programs',
    'assets/images/team/john-kamau.jpg',
    'John oversees all training programs and curriculum development. With a background in technical education, he ensures our programs meet industry standards and provide practical skills that lead to employment.',
    'MSc in Technical Education (Technical University of Kenya), BSc in Mechanical Engineering, Certified Training Professional (CTP)',
    12,
    '["Program Development", "Technical Training", "Curriculum Design", "Industry Partnerships"]',
    'john.kamau@skillsforafrica.org',
    '+254 733 234567',
    'https://linkedin.com/in/johnkamau',
    NULL,
    1,
    1,
    2,
    '2020-03-10',
    1
),
(
    'Mary Akinyi Ochieng',
    'Finance & Administration Manager',
    'Finance',
    'assets/images/team/mary-akinyi.jpg',
    'Mary manages all financial operations and administrative functions. Her expertise in non-profit financial management ensures transparency and accountability in all our operations.',
    'MSc in Finance (Strathmore University), CPA (K), Certified Non-profit Financial Professional',
    10,
    '["Financial Management", "Non-profit Accounting", "Budget Planning", "Compliance"]',
    'mary.akinyi@skillsforafrica.org',
    '+254 711 345678',
    'https://linkedin.com/in/maryakinyi',
    'https://twitter.com/maryakinyi',
    1,
    1,
    3,
    '2020-05-20',
    1
),
(
    'David Kiprop Rotich',
    'Field Coordinator',
    'Operations',
    'assets/images/team/david-kiprop.jpg',
    'David coordinates field activities and ensures effective program delivery in communities. His grassroots experience and community engagement skills are invaluable to our mission.',
    'Bachelor of Social Work (Moi University), Certificate in Community Development, Project Coordination Certification',
    8,
    '["Community Engagement", "Field Operations", "Program Coordination", "Stakeholder Management"]',
    'david.kiprop@skillsforafrica.org',
    '+254 721 456789',
    'https://linkedin.com/in/davidkiprop',
    NULL,
    0,
    1,
    4,
    '2021-02-15',
    1
),
(
    'Sarah Njeri Kimani',
    'Communications & Marketing Officer',
    'Communications',
    'assets/images/team/sarah-njeri.jpg',
    'Sarah manages our communications strategy, social media presence, and marketing initiatives. She ensures our impact stories reach the right audiences and attract support for our programs.',
    'Bachelor of Communications (University of Nairobi), Digital Marketing Certificate (Google), Public Relations Diploma',
    6,
    '["Digital Marketing", "Content Creation", "Public Relations", "Social Media Management"]',
    'sarah.njeri@skillsforafrica.org',
    '+254 712 567890',
    'https://linkedin.com/in/sarahnjeri',
    'https://twitter.com/sarahnjeri',
    0,
    1,
    5,
    '2021-08-01',
    1
),
(
    'Peter Mwangi Githui',
    'IT & Systems Coordinator',
    'Technology',
    'assets/images/team/peter-mwangi.jpg',
    'Peter maintains our technology infrastructure and develops digital solutions to enhance program delivery. His technical expertise supports both internal operations and student learning platforms.',
    'BSc in Information Technology (Jomo Kenyatta University), CCNA Certification, Web Development Certificate',
    7,
    '["Network Administration", "Web Development", "Database Management", "Technical Training"]',
    'peter.mwangi@skillsforafrica.org',
    '+254 734 678901',
    'https://linkedin.com/in/petermwangi',
    NULL,
    0,
    1,
    6,
    '2021-06-10',
    1
);

-- Verify the inserts
SELECT 'Partners inserted:' as message, COUNT(*) as count FROM partners WHERE created_by = 1;
SELECT 'Team members inserted:' as message, COUNT(*) as count FROM team_members WHERE created_by = 1;
