-- Sample Data for Chania Skills for Africa Database
-- Insert sample records for partners and team_members tables

USE chania_db;

-- Sample data for partners table
INSERT INTO partners (
    name, 
    slug, 
    description, 
    logo_path, 
    website_url, 
    contact_email, 
    contact_phone, 
    contact_person, 
    partnership_type, 
    partnership_level, 
    start_date, 
    is_featured, 
    is_active, 
    display_order, 
    created_by
) VALUES 
(
    'Kenya National Commission for UNESCO',
    'kenya-unesco',
    'UNESCO Kenya works to promote education, science, culture and communication for sustainable development in Kenya.',
    'uploads/partners/unesco-kenya.png',
    'https://www.unesco.org/en/fieldoffice/nairobi',
    'nairobi@unesco.org',
    '+254 20 762 4000',
    'Dr. Sarah Mwangi',
    'funding',
    'strategic',
    '2023-01-15',
    TRUE,
    TRUE,
    1,
    1
),
(
    'Safaricom Foundation',
    'safaricom-foundation',
    'Safaricom Foundation supports education and skills development initiatives across Kenya, focusing on digital literacy and entrepreneurship.',
    'uploads/partners/safaricom-foundation.png',
    'https://www.safaricom.co.ke/sustainability-report/safaricom-foundation',
    'foundation@safaricom.co.ke',
    '+254 722 000 000',
    'James Kimani',
    'funding',
    'strategic',
    '2023-03-10',
    TRUE,
    TRUE,
    2,
    1
),
(
    'Microsoft Kenya',
    'microsoft-kenya',
    'Microsoft Kenya provides technology solutions and digital skills training to empower local communities.',
    'uploads/partners/microsoft-kenya.png',
    'https://www.microsoft.com/en-ke/',
    'kenya@microsoft.com',
    '+254 20 286 0000',
    'Grace Wanjiku',
    'technology',
    'strategic',
    '2023-02-20',
    TRUE,
    TRUE,
    3,
    1
),
(
    'Kenya Association of Manufacturers',
    'kam',
    'KAM promotes manufacturing excellence and provides training opportunities for skilled workers in various industries.',
    'uploads/partners/kam.png',
    'https://kam.co.ke',
    'info@kam.co.ke',
    '+254 20 269 4086',
    'Peter Mwangi',
    'employment',
    'standard',
    '2023-05-01',
    FALSE,
    TRUE,
    4,
    1
),
(
    'German Development Cooperation (GIZ)',
    'giz-kenya',
    'GIZ Kenya supports vocational training and skills development programs in partnership with local institutions.',
    'uploads/partners/giz.png',
    'https://www.giz.de/en/worldwide/336.html',
    'giz-kenia@giz.de',
    '+254 20 4227000',
    'Hans Mueller',
    'funding',
    'standard',
    '2023-04-12',
    TRUE,
    TRUE,
    5,
    1
),
(
    'Technical University of Kenya',
    'tuk',
    'TUK collaborates in curriculum development and provides technical expertise for engineering and technology programs.',
    'uploads/partners/tuk.png',
    'https://tukenya.ac.ke',
    'info@tukenya.ac.ke',
    '+254 20 343 4601',
    'Prof. Francis Aduol',
    'training',
    'standard',
    '2023-06-15',
    FALSE,
    TRUE,
    6,
    1
);

-- Sample data for team_members table
INSERT INTO team_members (
    name,
    position,
    department,
    photo,
    bio,
    qualifications,
    experience_years,
    specialties,
    email,
    phone,
    linkedin,
    twitter,
    is_featured,
    is_active,
    position_order,
    hire_date,
    created_by
) VALUES 
(
    'Dr. Mary Wanjiku',
    'Executive Director',
    'Leadership',
    'uploads/team/mary-wanjiku.jpg',
    'Dr. Mary Wanjiku is an experienced educator and development professional with over 15 years of experience in skills development and community empowerment. She holds a PhD in Development Studies and has worked extensively across East Africa.',
    'PhD in Development Studies (University of Nairobi), MSc in Education Management (Kenyatta University), BSc in Agricultural Extension (Egerton University)',
    15,
    '["Leadership", "Development Programs", "Strategic Planning", "Community Engagement"]',
    'mary.wanjiku@skillsforafrica.org',
    '+254 722 123 456',
    'https://linkedin.com/in/marywanjiku',
    'https://twitter.com/marywanjiku',
    TRUE,
    TRUE,
    1,
    '2022-01-15',
    1
),
(
    'John Kamau',
    'Programs Manager',
    'Programs',
    'uploads/team/john-kamau.jpg',
    'John Kamau oversees the design and implementation of all skills development programs. With a background in project management and vocational training, he ensures programs meet the highest quality standards.',
    'MSc in Project Management (University of Nairobi), BSc in Mechanical Engineering (Jomo Kenyatta University), Certified Project Manager (PMP)',
    12,
    '["Project Management", "Vocational Training", "Quality Assurance", "Program Development"]',
    'john.kamau@skillsforafrica.org',
    '+254 733 234 567',
    'https://linkedin.com/in/johnkamau',
    NULL,
    TRUE,
    TRUE,
    2,
    '2022-03-01',
    1
),
(
    'Grace Muthoni',
    'Training Coordinator',
    'Training',
    'uploads/team/grace-muthoni.jpg',
    'Grace Muthoni coordinates all training activities and manages relationships with trainers and participants. She has extensive experience in adult education and capacity building.',
    'MSc in Adult Education (Kenyatta University), BSc in Education (Egerton University), Certificate in Training of Trainers',
    10,
    '["Adult Education", "Training Coordination", "Capacity Building", "Curriculum Development"]',
    'grace.muthoni@skillsforafrica.org',
    '+254 701 345 678',
    'https://linkedin.com/in/gracemuthoni',
    'https://twitter.com/gracemuthoni',
    TRUE,
    TRUE,
    3,
    '2022-05-15',
    1
),
(
    'Peter Ochieng',
    'Finance Manager',
    'Finance',
    'uploads/team/peter-ochieng.jpg',
    'Peter Ochieng manages all financial aspects of the organization, ensuring transparent and efficient use of resources. He has extensive experience in non-profit financial management.',
    'MBA in Finance (Strathmore University), BSc in Accounting (University of Nairobi), CPA Kenya, Certificate in Non-Profit Financial Management',
    8,
    '["Financial Management", "Budget Planning", "Financial Reporting", "Compliance"]',
    'peter.ochieng@skillsforafrica.org',
    '+254 712 456 789',
    'https://linkedin.com/in/peterochieng',
    NULL,
    FALSE,
    TRUE,
    4,
    '2022-08-01',
    1
),
(
    'Sarah Njeri',
    'Community Outreach Specialist',
    'Outreach',
    'uploads/team/sarah-njeri.jpg',
    'Sarah Njeri leads community engagement efforts and builds partnerships with local organizations. She has a passion for grassroots development and community mobilization.',
    'MSc in Community Development (University of Nairobi), BSc in Social Work (Kenyatta University), Certificate in Community Mobilization',
    7,
    '["Community Engagement", "Partnership Development", "Grassroots Mobilization", "Social Impact Assessment"]',
    'sarah.njeri@skillsforafrica.org',
    '+254 723 567 890',
    'https://linkedin.com/in/sarahnjeri',
    'https://twitter.com/sarahnjeri',
    TRUE,
    TRUE,
    5,
    '2022-10-15',
    1
),
(
    'David Kiprotich',
    'IT Support Specialist',
    'Administration',
    'uploads/team/david-kiprotich.jpg',
    'David Kiprotich manages the organization\'s IT infrastructure and provides technical support for all digital initiatives. He specializes in database management and web development.',
    'BSc in Computer Science (Moi University), Certificate in Network Administration, Certificate in Web Development',
    5,
    '["Database Management", "Web Development", "Network Administration", "Technical Support"]',
    'david.kiprotich@skillsforafrica.org',
    '+254 734 678 901',
    'https://linkedin.com/in/davidkirotich',
    NULL,
    FALSE,
    TRUE,
    6,
    '2023-01-10',
    1
),
(
    'Agnes Wambui',
    'Marketing and Communications Officer',
    'Communications',
    'uploads/team/agnes-wambui.jpg',
    'Agnes Wambui handles all marketing and communications activities, including social media management, content creation, and public relations.',
    'BSc in Mass Communication (University of Nairobi), Certificate in Digital Marketing, Certificate in Public Relations',
    4,
    '["Digital Marketing", "Content Creation", "Social Media Management", "Public Relations"]',
    'agnes.wambui@skillsforafrica.org',
    '+254 745 789 012',
    'https://linkedin.com/in/agneswambui',
    'https://twitter.com/agneswambui',
    FALSE,
    TRUE,
    7,
    '2023-03-15',
    1
);

-- Update application count for programs (optional - to make sample data more realistic)
UPDATE programs SET application_count = FLOOR(RAND() * 50) + 10 WHERE is_active = TRUE;

-- Update view count for programs (optional - to make sample data more realistic)
UPDATE programs SET view_count = FLOOR(RAND() * 500) + 100 WHERE is_active = TRUE;

SELECT 'Sample data inserted successfully!' as status;
